//-----------------------------------------------------------------------
// <copyright file="AccountContextModelSnapshot.cs" company="Starlight-Technology">
//     Author:  
//     Copyright (c) Starlight-Technology. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using System;

#nullable disable

namespace ROH.Context.Account.Migrations;

[DbContext(typeof(AccountContext))]
partial class AccountContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "ROH.Context.Account.Entities.Account",
            b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateOnly>("BirthDate").HasColumnType("date");

                b.Property<Guid>("Guid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<long>("IdUser").HasColumnType("bigint");

                b.Property<string>("RealName").HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Accounts");
            });

        modelBuilder.Entity(
            "ROH.Context.Account.Entities.User",
            b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("Email").HasColumnType("text");

                b.Property<Guid>("Guid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<long>("IdAccount").HasColumnType("bigint");

                b.Property<byte[]>("PasswordHash").HasColumnType("bytea");

                b.Property<byte[]>("Salt").HasColumnType("bytea");

                b.Property<string>("UserName").HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("IdAccount").IsUnique();

                b.ToTable("Users");
            });

        modelBuilder.Entity(
            "ROH.Context.Account.Entities.User",
            b =>
            {
                b.HasOne("ROH.Context.Account.Entities.Account", "Account")
                    .WithOne("User")
                    .HasForeignKey("ROH.Context.Account.Entities.User", "IdAccount")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Account");
            });

        modelBuilder.Entity("ROH.Context.Account.Entities.Account", b => b.Navigation("User"));
#pragma warning restore 612, 618
    }
}
