<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8f2f5379-61d9-48ba-a579-1d9eeffbc44a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <Configurations>Debug;Release;Test</Configurations>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageReference Include="Grpc.AspNetCore.Server" Version="2.80.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.80.0" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageReference Include="Grpc.Tools" Version="2.81.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MessagePack" Version="3.1.7" />
    <PackageReference Include="MessagePack.Annotations" Version="3.1.7" />
    <PackageReference Include="MessagePackAnalyzer" Version="3.1.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\ROH.Contracts\ROH.Contracts.csproj" />
    <ProjectReference Include="..\..\Common\ROH.Utils\ROH.Utils.csproj" />
    <ProjectReference Include="..\..\Database\ROH.Context.Player\ROH.Context.Player.csproj" />
    <ProjectReference Include="..\..\Database\ROH.Context.Player.Mongo\ROH.Context.Player.Mongo.csproj" />
    <ProjectReference Include="..\..\Service\ROH.Service.Exception\ROH.Service.Exception.csproj" />
    <ProjectReference Include="..\..\Service\ROH.Service.Player.WebSocket\ROH.Service.Player.WebSocket.csproj" />
    <ProjectReference Include="..\..\Service\ROH.Service.WebSocket\ROH.Service.WebSocket.csproj" />
  </ItemGroup>

</Project>
