//-----------------------------------------------------------------------
// <copyright file="VersionContextModelSnapshot.cs" company="Starlight-Technology">
//     Author:  
//     Copyright (c) Starlight-Technology. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using System;

#nullable disable

namespace ROH.Context.Version.Migrations;

[DbContext(typeof(VersionContext))]
partial class VersionContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "ROH.Context.Version.Entities.GameVersion",
            b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<Guid>("Guid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid")
                    .HasDefaultValueSql("gen_random_uuid()");

                b.Property<int>("Release").HasColumnType("integer");

                b.Property<DateTime?>("ReleaseDate").HasColumnType("timestamp with time zone");

                b.Property<bool>("Released").HasColumnType("boolean");

                b.Property<int>("Review").HasColumnType("integer");

                b.Property<int>("Version").HasColumnType("integer");

                b.Property<DateTime?>("VersionDate").HasColumnType("timestamp with time zone");

                b.HasKey("Id");

                b.ToTable("GameVersions");
            });
#pragma warning restore 612, 618
    }
}
