//-----------------------------------------------------------------------
// <copyright file="LogContextModelSnapshot.cs" company="Starlight-Technology">
//     Author:  
//     Copyright (c) Starlight-Technology. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using System;

#nullable disable

namespace ROH.Context.Log.Migrations;

[DbContext(typeof(LogContext))]
partial class LogContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "ROH.Context.Log.Entities.Log",
            b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTime>("Date").HasColumnType("timestamp with time zone");

                b.Property<string>("Message").IsRequired().HasColumnType("text");

                b.Property<int>("Severity").HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Logs");
            });
#pragma warning restore 612, 618
    }
}
